title: KhTech - Заметки
description: >- 
  Рабочие заметки и инструкции
baseurl: ""
url: "https://notes.khudoley.pro/"

# Тема и плагины
remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme

# Настройки темы
show_downloads: false

# Настройки SEO
title: KhTech - Заметки
description: >- # Описание для SEO
  Рабочие заметки и инструкции

# Настройки построения
permalink: /:year/:month/:day/:title/ # Формат постоянной ссылки для постов
paginate: 5 # Количество постов на странице
